import React, { useState, useContext } from 'react';
import { useNavigate } from 'react-router-dom';
import { AuthContext } from '../context/AuthContext';
import './Support.css'; // Assuming you have a CSS file for this

// Utility to load the Razorpay script dynamically
const loadScript = (src) => {
  return new Promise((resolve) => {
    const script = document.createElement("script");
    script.src = src;
    script.onload = () => resolve(true);
    script.onerror = () => resolve(false);
    document.body.appendChild(script);
  });
};

export default function Support() {
  const { user } = useContext(AuthContext);
  const navigate = useNavigate();
  const [amount, setAmount] = useState(501); // Default offering
  const [purpose, setPurpose] = useState('General Seva');
  const [isProcessing, setIsProcessing] = useState(false);

  const displayRazorpay = async (e) => {
    e.preventDefault();

    // 1. Ensure user is logged in
    if (!user) {
      alert("Please log in or register to make a donation.");
      navigate('/login');
      return;
    }

    setIsProcessing(true);

    // 2. Load the Razorpay SDK
    const res = await loadScript("https://checkout.razorpay.com/v1/checkout.js");
    if (!res) {
      alert("Razorpay SDK failed to load. Are you online?");
      setIsProcessing(false);
      return;
    }

    try {
      // 3. Ask your backend to create an Order
      const orderData = await fetch(`${import.meta.env.VITE_API_URL}/api/donations/create-order`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${user.token}`
        },
        body: JSON.stringify({ amount, purpose })
      }).then(t => t.json());

      if (!orderData.success) {
        alert("Server error. Please try again.");
        setIsProcessing(false);
        return;
      }

      // 4. Configure the Razorpay Checkout Popup
      const options = {
        key: import.meta.env.VITE_RAZORPAY_KEY_ID, // MUST match your public .env key exactly
        amount: orderData.order.amount,
        currency: orderData.order.currency,
        name: "Achyuta Ananta Ashram",
        description: `Donation for ${purpose}`,
        image: "https://your-ashram-logo-url.com/logo.png", // Optional: Add your logo URL
        order_id: orderData.order.id, // The ID generated by your Node backend

        // 5. This handler runs when the payment is successful
        handler: async function (response) {
          const verificationData = {
            razorpay_order_id: response.razorpay_order_id,
            razorpay_payment_id: response.razorpay_payment_id,
            razorpay_signature: response.razorpay_signature,
            donationId: orderData.donationId // Passing the DB ID we saved earlier
          };

          // 6. Send signature to backend for cryptographic verification
          const verifyRes = await fetch(`${import.meta.env.VITE_API_URL}/api/donations/verify-payment`, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': `Bearer ${user.token}`
            },
            body: JSON.stringify(verificationData)
          }).then(t => t.json());

          if (verifyRes.success) {
            alert(`Hari Om! Payment successful. Payment ID: ${response.razorpay_payment_id}`);
            navigate('/my-profile'); // Send them to see their updated Seva history!
          } else {
            alert("Payment verification failed.");
          }
        },
        prefill: {
          name: user.name,
          email: user.email,
        },
        theme: {
          color: "#e67e22" // Ashram orange theme
        }
      };

      // 7. Open the checkout window
      const paymentObject = new window.Razorpay(options);
      paymentObject.open();

    } catch (error) {
      console.error(error);
      alert("Something went wrong during checkout.");
    }

    setIsProcessing(false);
  };

  return (
    <div className="support-page" style={{ padding: '80px 20px', minHeight: '80vh', textAlign: 'center', backgroundColor: '#121212', color: '#fff' }}>
      <h2>Support the Ashram</h2>
      <p style={{ color: '#ccc', marginBottom: '40px' }}>Your contributions sustain our daily operations and spiritual programs.</p>

      <form onSubmit={displayRazorpay} style={{ maxWidth: '400px', margin: '0 auto', backgroundColor: '#1e1e1e', padding: '30px', borderRadius: '8px' }}>
        
        <div style={{ marginBottom: '20px', textAlign: 'left' }}>
          <label style={{ display: 'block', color: '#e67e22', marginBottom: '8px' }}>Seva Purpose</label>
          <select value={purpose} onChange={(e) => setPurpose(e.target.value)} required style={{ width: '100%', padding: '10px', backgroundColor: '#242424', color: '#fff', border: '1px solid #444', borderRadius: '4px' }}>
            <option value="General Seva">General Seva</option>
            <option value="Anna Daan (Food)">Anna Daan (Food)</option>
            <option value="Gau Seva (Cows)">Gau Seva (Cows)</option>
            <option value="Vedic Education">Vedic Education</option>
          </select>
        </div>

        <div style={{ marginBottom: '30px', textAlign: 'left' }}>
          <label style={{ display: 'block', color: '#e67e22', marginBottom: '8px' }}>Amount (₹)</label>
          <input 
            type="number" 
            min="100" 
            value={amount} 
            onChange={(e) => setAmount(e.target.value)} 
            required 
            style={{ width: '100%', padding: '10px', backgroundColor: '#242424', color: '#fff', border: '1px solid #444', borderRadius: '4px' }}
          />
        </div>

        <button 
          type="submit" 
          disabled={isProcessing}
          style={{ width: '100%', padding: '15px', backgroundColor: '#e67e22', color: '#fff', border: 'none', borderRadius: '6px', fontSize: '1.1rem', fontWeight: 'bold', cursor: isProcessing ? 'not-allowed' : 'pointer' }}
        >
          {isProcessing ? 'Processing...' : `Donate ₹${amount}`}
        </button>
      </form>
    </div>
  );
}